version: '3.7'

services:

  datapipeui:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: datapipeui
    ports:
    - "4200:4200"

    # usual way to ignore node_modules subfolder
    # volumes:
    #- .:/app
    #- /app/node_modules
    
    # workaround to Docker issue https://github.com/moby/moby/issues/38564
    volumes:
    - ./e2e:/app/e2e
    - ./src:/app/src

networks:
  default:
    external:
      name: datapipe-network