services:

  httpdatapipe:
    image: httpdatapipe:latest
    build:
      context: .
      args:
        NG_BUILD_OPTS: build
    container_name: httpdatapipe
    ports:
    - "8080:80"

networks:
  default:
      name: datapipe-network
      external: true