# build 
FROM node:12.14.1-alpine AS datapipeUI-build
USER node
WORKDIR /app
COPY . .
USER root
RUN npm install
RUN npm run build

# run
FROM nginx AS datapipeUI-run
COPY --from=datapipeUI-build /app/dist/DataPipeUI /usr/share/nginx/html